/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apresentacao;

import java.awt.Color;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Locale;
import java.util.Map.Entry;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import persistencia.ConexaoSQLite;
import persistencia.OSInfo;

/**
 *
 * @author iapereira
 */
public class Main extends javax.swing.JFrame {

    private final HashMap<Integer, JButton> violao;
    private int idShapeRestaurado;

    /**
     * Creates new form NewJFrame
     */
    public Main() throws SQLException {
        initComponents();        
        String path = "src/";
        File file = new File(path);
        String absolutePath = file.getAbsolutePath();        
        String path_violao = "";
        // linux
        if (OSInfo.getOs() == OSInfo.OS.UNIX) {            
            path_violao = absolutePath.replace("dist/", "") + "/violao.png";
        } else { // windows
            path = "src\\";
            file = new File(path);
            absolutePath = file.getAbsolutePath();
            path_violao = absolutePath.replace("dist\\", "") + "\\violao.png";            
        }        
        jButton1.setIcon(new javax.swing.ImageIcon(path_violao)); 
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        Locale locale = new Locale("pt", "BR");
        JOptionPane.setDefaultLocale(locale);
        this.jButton45.setVisible(false);
        violao = new HashMap();
        violao.put(2, jButton2);
        violao.put(3, jButton3);
        violao.put(4, jButton4);
        violao.put(5, jButton5);
        violao.put(6, jButton6);
        violao.put(7, jButton7);
        violao.put(8, jButton8);
        violao.put(9, jButton9);
        violao.put(10, jButton10);
        violao.put(11, jButton11);
        violao.put(12, jButton12);
        violao.put(13, jButton13);
        violao.put(14, jButton14);
        violao.put(15, jButton15);
        violao.put(16, jButton16);
        violao.put(17, jButton17);
        violao.put(18, jButton18);
        violao.put(19, jButton19);
        violao.put(20, jButton20);
        violao.put(21, jButton21);
        violao.put(22, jButton22);
        violao.put(23, jButton23);
        violao.put(24, jButton24);
        violao.put(25, jButton25);
        violao.put(26, jButton26);
        violao.put(27, jButton27);
        violao.put(28, jButton28);
        violao.put(29, jButton29);
        violao.put(30, jButton30);
        violao.put(31, jButton31);
        violao.put(32, jButton32);
        violao.put(33, jButton33);
        violao.put(34, jButton34);
        violao.put(35, jButton35);
        violao.put(36, jButton36);
        violao.put(37, jButton37);
        violao.put(38, jButton38);
        violao.put(39, jButton39);
        violao.put(40, jButton40);
        violao.put(41, jButton41);
        violao.put(42, jButton42);
        violao.put(43, jButton43);

        this.jButton_imprimir.addActionListener(new ComponentPrinter(this.jPanel1));

        reiniciarViolao();

//        Iterator iterator = this.violao.entrySet().iterator();
//        while (iterator.hasNext()) {
//            Entry<Integer, JButton> entry = (Entry) iterator.next();
//            JButton button = entry.getValue();
//            button.setText("---");
//        }
        ConexaoSQLite myConnection = new ConexaoSQLite();
        Connection connection = myConnection.getMyConnection();
        String sql = "SELECT * from shapes ORDER BY id;";
        PreparedStatement preparedStatement = connection.prepareStatement(sql);
        ResultSet rs = preparedStatement.executeQuery();
        while (rs.next()) {
            this.list1.add(rs.getInt("id") + "-" + rs.getString("nome"));
        }
        preparedStatement.close();
        connection.close();

//        this.jButton2.setText("");
//        this.jButton2.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_limpar = new javax.swing.JButton();
        jButton_reiniciar = new javax.swing.JButton();
        jButton_imprimir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        list1 = new java.awt.List();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton_limpar.setText("Limpar demais botões");
        jButton_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_limparActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_limpar);
        jButton_limpar.setBounds(200, 360, 200, 23);

        jButton_reiniciar.setText("Reiniciar");
        jButton_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_reiniciarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_reiniciar);
        jButton_reiniciar.setBounds(30, 380, 160, 23);

        jButton_imprimir.setText("Imprimir");
        getContentPane().add(jButton_imprimir);
        jButton_imprimir.setBounds(410, 380, 150, 23);

        jPanel1.setLayout(null);

        jButton2.setText("jButton2");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(30, 40, 78, 23);

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(140, 40, 78, 23);

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(240, 40, 78, 23);

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(350, 40, 78, 23);

        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(460, 40, 78, 23);

        jButton7.setText("jButton7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(560, 40, 78, 23);

        jButton8.setText("jButton8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(670, 40, 78, 23);

        jButton9.setText("jButton9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(30, 100, 78, 23);

        jButton10.setText("jButton10");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(140, 100, 85, 23);

        jButton11.setText("jButton11");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(240, 100, 85, 23);

        jButton12.setText("jButton12");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);
        jButton12.setBounds(350, 100, 85, 23);

        jButton13.setText("jButton13");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);
        jButton13.setBounds(460, 100, 85, 23);

        jButton14.setText("jButton14");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14);
        jButton14.setBounds(560, 100, 85, 23);

        jButton15.setText("jButton15");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15);
        jButton15.setBounds(670, 100, 85, 23);

        jButton16.setText("jButton16");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16);
        jButton16.setBounds(30, 160, 85, 23);

        jButton17.setText("jButton17");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17);
        jButton17.setBounds(140, 160, 85, 23);

        jButton18.setText("jButton18");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18);
        jButton18.setBounds(240, 160, 85, 23);

        jButton19.setText("jButton19");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19);
        jButton19.setBounds(350, 160, 85, 23);

        jButton20.setText("jButton20");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton20);
        jButton20.setBounds(460, 160, 85, 23);

        jButton21.setText("jButton21");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton21);
        jButton21.setBounds(560, 160, 85, 23);

        jButton22.setText("jButton22");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton22);
        jButton22.setBounds(670, 160, 85, 23);

        jButton24.setText("jButton24");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton24);
        jButton24.setBounds(140, 220, 85, 23);

        jButton25.setText("jButton25");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton25);
        jButton25.setBounds(240, 220, 85, 23);

        jButton26.setText("jButton26");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton26);
        jButton26.setBounds(350, 220, 85, 23);

        jButton27.setText("jButton27");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton27);
        jButton27.setBounds(460, 220, 85, 23);

        jButton28.setText("jButton28");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton28);
        jButton28.setBounds(560, 220, 85, 23);

        jButton29.setText("jButton29");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton29);
        jButton29.setBounds(670, 220, 85, 23);

        jButton30.setText("jButton30");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton30);
        jButton30.setBounds(30, 280, 85, 23);

        jButton23.setText("jButton23");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton23);
        jButton23.setBounds(30, 220, 85, 23);

        jButton31.setText("jButton31");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton31);
        jButton31.setBounds(140, 280, 85, 23);

        jButton32.setText("jButton32");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton32);
        jButton32.setBounds(240, 280, 85, 23);

        jButton33.setText("jButton33");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton33);
        jButton33.setBounds(350, 280, 85, 23);

        jButton34.setText("jButton34");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton34);
        jButton34.setBounds(460, 280, 85, 23);

        jButton35.setText("jButton35");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton35);
        jButton35.setBounds(560, 280, 85, 23);

        jButton36.setText("jButton36");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton36);
        jButton36.setBounds(670, 280, 85, 23);

        jButton37.setText("jButton37");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton37);
        jButton37.setBounds(30, 340, 85, 23);

        jButton38.setText("jButton38");
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton38);
        jButton38.setBounds(140, 340, 85, 23);

        jButton39.setText("jButton39");
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton39);
        jButton39.setBounds(250, 340, 85, 23);

        jButton40.setText("jButton40");
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton40);
        jButton40.setBounds(350, 340, 85, 23);

        jButton41.setText("jButton41");
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton41);
        jButton41.setBounds(460, 340, 85, 23);

        jButton42.setText("jButton42");
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton42);
        jButton42.setBounds(560, 340, 85, 23);

        jButton43.setText("jButton43");
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton43);
        jButton43.setBounds(670, 340, 85, 23);

        jButton1.setPreferredSize(new java.awt.Dimension(500, 500));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(6, 43, 770, 322);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -20, 790, 390);

        jButton44.setText("Salvar Como...");
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton44);
        jButton44.setBounds(590, 380, 130, 23);

        list1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        list1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list1ActionPerformed(evt);
            }
        });
        getContentPane().add(list1);
        list1.setBounds(810, 30, 170, 290);

        jButton45.setText("Atualizar");
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton45);
        jButton45.setBounds(740, 380, 81, 23);

        jButton46.setText("Retornar demais botões");
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton46);
        jButton46.setBounds(200, 390, 200, 23);

        jMenu1.setText("Menu");

        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sobre");

        jMenuItem1.setText("?");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        colocarDedo(2);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        colocarDedo(3);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        colocarDedo(4);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        colocarDedo(5);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        colocarDedo(6);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        colocarDedo(7);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        colocarDedo(8);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        colocarDedo(9);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        colocarDedo(10);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_limparActionPerformed
        // TODO add your handling code here:
        Iterator iterator = this.violao.entrySet().iterator();
        while (iterator.hasNext()) {
            Entry<Integer, JButton> entry = (Entry) iterator.next();
            JButton button = entry.getValue();
            if (!button.getText().equals("1") && !button.getText().equals("2") && !button.getText().equals("3") && !button.getText().equals("4")) {
                button.setVisible(false);
            }
        }
    }//GEN-LAST:event_jButton_limparActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        colocarDedo(11);

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        colocarDedo(12);

    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        colocarDedo(13);

    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        colocarDedo(14);

    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        colocarDedo(15);

    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        colocarDedo(16);

    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        colocarDedo(17);

    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        colocarDedo(18);

    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        colocarDedo(19);

    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        colocarDedo(20);

    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        colocarDedo(21);

    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        colocarDedo(22);

    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        colocarDedo(24);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
        colocarDedo(25);
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
        colocarDedo(26);
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
        colocarDedo(27);
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
        colocarDedo(28);
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        // TODO add your handling code here:
        colocarDedo(29);
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
        colocarDedo(30);
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        colocarDedo(23);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Desenvolvido por Igor Pereira", "Guitar Scale", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:
        colocarDedo(31);
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:
        colocarDedo(32);
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        // TODO add your handling code here:
        colocarDedo(33);
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        // TODO add your handling code here:
        colocarDedo(34);
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        // TODO add your handling code here:
        colocarDedo(35);
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        // TODO add your handling code here:
        colocarDedo(36);
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        // TODO add your handling code here:
        colocarDedo(37);
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        // TODO add your handling code here:
        colocarDedo(38);
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        // TODO add your handling code here:
        colocarDedo(39);
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
        // TODO add your handling code here:
        colocarDedo(40);
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        // TODO add your handling code here:
        colocarDedo(41);
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
        // TODO add your handling code here:
        colocarDedo(42);
    }//GEN-LAST:event_jButton42ActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
        // TODO add your handling code here:
        colocarDedo(43);
    }//GEN-LAST:event_jButton43ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        dispose();
        System.exit(0); //calling the method is a must

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_reiniciarActionPerformed
        // TODO add your handling code here:
        reiniciarViolao();
    }//GEN-LAST:event_jButton_reiniciarActionPerformed

    private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44ActionPerformed
        try {
            int id = 0;
            String nome = JOptionPane.showInputDialog(this, "Qual nome?", "GuitarScale", JOptionPane.INFORMATION_MESSAGE);
            if (nome != null) {
                if (!nome.isEmpty()) {
                    ConexaoSQLite myConnection = new ConexaoSQLite();
                    Connection connection = myConnection.getMyConnection();
                    String sql = "INSERT INTO shapes (nome) values (?) RETURNING id;";
                    PreparedStatement preparedStatement = connection.prepareStatement(sql);
                    preparedStatement.setString(1, nome);
                    ResultSet rs = preparedStatement.executeQuery();
                    if (rs.next()) {
                        id = rs.getInt("id");
                        preparedStatement.close();

                        Iterator iterator = this.violao.entrySet().iterator();
                        while (iterator.hasNext()) {
                            Entry<Integer, JButton> entry = (Entry) iterator.next();
                            int idButton = entry.getKey();
                            JButton button = entry.getValue();
                            if (button.getText().equals("1") || button.getText().equals("2") || button.getText().equals("3") || button.getText().equals("4")) {
                                sql = "INSERT INTO notas (botao, dedo, dominante, shape_id) values (?, ?, ?, ?);";
                                preparedStatement = connection.prepareStatement(sql);
                                preparedStatement.setString(1, String.valueOf(idButton));
                                preparedStatement.setString(2, button.getText());
                                if (button.getBackground() == Color.red) {
                                    preparedStatement.setBoolean(3, true);
                                } else {
                                    preparedStatement.setBoolean(3, false);
                                }
                                preparedStatement.setInt(4, id);
                                preparedStatement.execute();
                                preparedStatement.close();
                            }
                        }
                    }
                    this.list1.add(id + "-" + nome);
                    connection.close();
                } else {
                    JOptionPane.showMessageDialog(this, "Favor preencher o nome do shape!", "Guitar Scale", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton44ActionPerformed

    private void list1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list1ActionPerformed
        int resp = JOptionPane.showConfirmDialog(this, "Restaurar?", "GuitarScale", JOptionPane.YES_NO_OPTION);
        boolean resposta = (resp == JOptionPane.YES_OPTION);
        if (!resposta) {
            resp = JOptionPane.showConfirmDialog(this, "Deletar?", "GuitarScale", JOptionPane.YES_NO_OPTION);
            resposta = (resp == JOptionPane.YES_OPTION);
            if (resposta) {
//                deletar
                if (!this.list1.getSelectedItem().isEmpty()) {
                    int id = Integer.parseInt(this.list1.getSelectedItem().split("-")[0]);
                    try {
                        ConexaoSQLite myConnection = new ConexaoSQLite();
                        Connection connection = myConnection.getMyConnection();
                        String sql = "DELETE FROM notas where shape_id = ?;";
                        PreparedStatement preparedStatement;
                        preparedStatement = connection.prepareStatement(sql);
                        preparedStatement.setInt(1, id);
                        preparedStatement.execute();
                        sql = "DELETE FROM shapes where id = ?;";
                        preparedStatement = connection.prepareStatement(sql);
                        preparedStatement.setInt(1, id);
                        preparedStatement.execute();
                        connection.close();
                        this.list1.remove(this.list1.getSelectedItem());
                        this.jButton45.setVisible(false);
                        this.idShapeRestaurado = 0;
                    } catch (SQLException ex) {
                        Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Selecione algum shape na lista!", "Guitar Scale", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } else {
            // restaurar
            if (!this.list1.getSelectedItem().isEmpty()) {
                this.reiniciarViolao();
                int id = Integer.parseInt(this.list1.getSelectedItem().split("-")[0]);
                ConexaoSQLite myConnection = new ConexaoSQLite();
                Connection connection = myConnection.getMyConnection();
                String sql = "SELECT * from notas where shape_id = ?;";
                PreparedStatement preparedStatement = null;
                try {
                    preparedStatement = connection.prepareStatement(sql);
                    preparedStatement.setInt(1, id);
                    ResultSet rs = preparedStatement.executeQuery();
                    while (rs.next()) {
                        JButton button = this.violao.get(Integer.valueOf(rs.getString("botao")));
                        button.setText(rs.getString("dedo"));
                        if (rs.getBoolean("dominante")) {
                            button.setForeground(Color.white);
                            button.setBackground(Color.red);
                        } else {
                            button.setForeground(Color.white);
                            button.setBackground(Color.BLACK);
                        }
                    }
                    preparedStatement.close();
                    connection.close();

                    this.idShapeRestaurado = id;

                    this.jButton45.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Selecione algum shape na lista!", "Guitar Scale", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_list1ActionPerformed

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
        if (this.idShapeRestaurado > 0) {
            ConexaoSQLite myConnection = new ConexaoSQLite();
            Connection connection = myConnection.getMyConnection();
            PreparedStatement preparedStatement;
            try {
                preparedStatement = connection.prepareStatement("SELECT * FROM shapes where id = ?");
                preparedStatement.setInt(1, this.idShapeRestaurado);
                ResultSet rs = preparedStatement.executeQuery();
                if (rs.next()) {
                    int resp = JOptionPane.showConfirmDialog(this, "Você deseja mesmo atualizar " + this.idShapeRestaurado+"-"+rs.getString("nome") + " ?", "GuitarScale", JOptionPane.YES_NO_OPTION);
                    boolean resposta = (resp == JOptionPane.YES_OPTION);
                    if (resposta) {
                        try {
                            preparedStatement = connection.prepareStatement("DELETE FROM notas where shape_id = ?");
                            preparedStatement.setInt(1, this.idShapeRestaurado);
                            preparedStatement.execute();
                            preparedStatement.close();
                        } catch (SQLException ex) {
                            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        Iterator iterator = this.violao.entrySet().iterator();
                        while (iterator.hasNext()) {
                            Entry<Integer, JButton> entry = (Entry) iterator.next();
                            int idButton = entry.getKey();
                            JButton button = entry.getValue();
                            if (button.getText().equals("1") || button.getText().equals("2") || button.getText().equals("3") || button.getText().equals("4")) {
                                String sql = "INSERT INTO notas (botao, dedo, dominante, shape_id) values (?, ?, ?, ?);";
                                try {
                                    preparedStatement = connection.prepareStatement(sql);
                                    preparedStatement.setString(1, String.valueOf(idButton));
                                    preparedStatement.setString(2, button.getText());
                                    if (button.getBackground() == Color.red) {
                                        preparedStatement.setBoolean(3, true);
                                    } else {
                                        preparedStatement.setBoolean(3, false);
                                    }
                                    preparedStatement.setInt(4, this.idShapeRestaurado);
                                    preparedStatement.execute();
                                    preparedStatement.close();
                                } catch (SQLException ex) {
                                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
//                                    break;
                                }
                            }
                        }
                        JOptionPane.showMessageDialog(this, "Shape atualizado com sucesso!", "Guitar Scale", JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Shape não encontrado!", "Guitar Scale", JOptionPane.ERROR_MESSAGE);
                }
                preparedStatement.close();
                connection.close();
            } catch (SQLException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Favor restaurar algum shape antes de atualizá-lo!", "Guitar Scale", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
        Iterator iterator = this.violao.entrySet().iterator();
        while (iterator.hasNext()) {
            Entry<Integer, JButton> entry = (Entry) iterator.next();
            JButton button = entry.getValue();           
            if (!button.getText().equals("1") && !button.getText().equals("2") && !button.getText().equals("3") && !button.getText().equals("4")){            
                button.setVisible(true);
                button.setBackground(Color.LIGHT_GRAY);
                button.setForeground(Color.black);
                button.setText("---");
            }
        }
    }//GEN-LAST:event_jButton46ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Main().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton_imprimir;
    private javax.swing.JButton jButton_limpar;
    private javax.swing.JButton jButton_reiniciar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private java.awt.List list1;
    // End of variables declaration//GEN-END:variables

    private void colocarDedo(int i) {
        JButton button = this.violao.get(i);

        String dedo = (String) JOptionPane.showInputDialog(this, "Qual dedo será (1, 2, 3 ou 4) (0 reseta)? ", "Guitar Scale", JOptionPane.QUESTION_MESSAGE, null, null, "1");
        if (dedo == null) {
            dedo = "1";
        }
        if (dedo.equals("1") || dedo.equals("2") || dedo.equals("3") || dedo.equals("4")) {
            int dominante = JOptionPane.showConfirmDialog(this, "É dominante?", "Selecione", JOptionPane.YES_NO_OPTION);
            boolean dominanteResposta = (dominante == JOptionPane.YES_OPTION);
            button.setText(dedo.trim());
            if (dominanteResposta) {
                button.setForeground(Color.white);
                button.setBackground(Color.red);
            } else {
                button.setForeground(Color.white);
                button.setBackground(Color.BLACK);
            }
        } else if (dedo.equals("0")) {
            button.setVisible(true);
            button.setBackground(Color.LIGHT_GRAY);
            button.setForeground(Color.black);
            button.setText("---");
        } else {
            JOptionPane.showMessageDialog(this, "Opção inválida!", "Guitar Scale", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void reiniciarViolao() {
        this.idShapeRestaurado = 0;
        this.jButton45.setVisible(false);

        Iterator iterator = this.violao.entrySet().iterator();
        while (iterator.hasNext()) {
            Entry<Integer, JButton> entry = (Entry) iterator.next();
            JButton button = entry.getValue();
            button.setVisible(true);
            button.setBackground(Color.LIGHT_GRAY);
            button.setForeground(Color.black);
            button.setText("---");
//            if (!button.getText().equals("1") && !button.getText().equals("2") && !button.getText().equals("3") && !button.getText().equals("4")){            
//                button.setVisible(false);
//            }
        }
    }
}
